/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalo
 */
public final class ViewIngreso extends javax.swing.JFrame {

    /**
     * Creates new form ViewIngreso
     */
    public ViewIngreso() {
        initComponents();
        cargarPuestos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        lblPuestosDisponibles = new javax.swing.JLabel();
        lstPuestos = new java.awt.List();
        btnSeleccionarPuesto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPuestosDisponibles.setText("Puestos disponibles:");

        btnSeleccionarPuesto.setText("Seleccionar");
        btnSeleccionarPuesto.setAutoscrolls(true);
        btnSeleccionarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPuestoActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar un Puesto de Trabajo:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblPuestosDisponibles)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lstPuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSalir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSeleccionarPuesto))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPuestosDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarPuesto)
                    .addComponent(btnSalir))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPuestoActionPerformed
        String puestoSeleccionado = lstPuestos.getSelectedItem();
        int PuestoID = Integer.parseInt(puestoSeleccionado);	
        ControllerSistema.getInstancia().setPuestoTrabajador(PuestoID);
        new ViewAtender().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSeleccionarPuestoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(ControllerSistema.getInstancia().getSiguienteNumeroAtencion() == null) {
            dispose();
            new ViewLogin().setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null,"No puedes salir del puesto si tienes números asignados o en espera");
        }
    }//GEN-LAST:event_btnSalirActionPerformed
    
    public void cargarPuestos() {
        String[] puestos = ControllerSistema.getInstancia().getPuestosDisponibles();

        for(String s : puestos) {
            if(s != null) {
                lstPuestos.add(s);
            }
        }
        lstPuestos.select(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarPuesto;
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPuestosDisponibles;
    private java.awt.List lstPuestos;
    // End of variables declaration//GEN-END:variables
}
